
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.githubusercontent.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

platform: x64

environment:
  R_VERSION: devel
  R_ARCH: x64
  GCC_PATH: mingw_64
  USE_RTOOLS: yes
  R_BUILD_ARGS: --resave-data --compact-vignettes=gs+qpdf
  R_CHECK_ARGS:


build_script:
  - travis-tool.sh install_r devtools
  - travis-tool.sh install_bioc_deps

#before_test:
#  # Install pandoc
#  - cinst pandoc
#  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\;C:\Program Files\Pandoc\"
#  - pandoc -v
#  # Install miktex
#  - ps: choco install -y miktex

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
